### ISSUE TITLE
Error: Error reading cache files

### ISSUE THREAD

**Issue by benjick** [KajSzy/next-cache-toolbar#1]
Hello!

Just tried installing this, I'm running next 14.1.0. Getting this error:

```
⨯ ../node_modules/.pnpm/next-cache-toolbar@0.1.1_@types+react-dom@18.2.19_@types+react@18.2.57_next@14.1.0_react-dom@_sjr35uyvym3e66scuvb5ztjxci/node_modules/next-cache-toolbar/dist/es/index.mjs (50:14) @ Error
⨯ Internal error: Error: Error reading cache files
   at getCacheFiles (../../node_modules/.pnpm/next-cache-toolbar@0.1.1_@types+react-dom@18.2.19_@types+react@18.2.57_next@14.1.0_react-dom@_sjr35uyvym3e66scuvb5ztjxci/node_modules/next-cache-toolbar/dist/es/index.mjs:69:15)
   at async NextCacheToolbar (../../node_modules/.pnpm/next-cache-toolbar@0.1.1_@types+react-dom@18.2.19_@types+react@18.2.57_next@14.1.0_react-dom@_sjr35uyvym3e66scuvb5ztjxci/node_modules/next-cache-toolbar/dist/es/index.mjs:73:19)
@nextgen/merlin:dev: null
⨯ ../node_modules/.pnpm/next-cache-toolbar@0.1.1_@types+react-dom@18.2.19_@types+react@18.2.57_next@14.1.0_react-dom@_sjr35uyvym3e66scuvb5ztjxci/node_modules/next-cache-toolbar/dist/es/index.mjs (50:14) @ Error
⨯ Internal error: Error: Error reading cache files
   at getCacheFiles (../../node_modules/.pnpm/next-cache-toolbar@0.1.1_@types+react-dom@18.2.19_@types+react@18.2.57_next@14.1.0_react-dom@_sjr35uyvym3e66scuvb5ztjxci/node_modules/next-cache-toolbar/dist/es/index.mjs:69:15)
   at async NextCacheToolbar (../../node_modules/.pnpm/next-cache-toolbar@0.1.1_@types+react-dom@18.2.19_@types+react@18.2.57_next@14.1.0_react-dom@_sjr35uyvym3e66scuvb5ztjxci/node_modules/next-cache-toolbar/dist/es/index.mjs:73:19)
@nextgen/merlin:dev: digest: "3930452139"
```

**Comment by KajSzy** [comment]
Could you look into `.next/cache/fetch-cache` folder and check if there is any non-ordinary file?
Most if not all of them should be named as hash.
If there is nothing extra ordinary, if you could find file that isn't matching JSON format.

Later today I will release `0.1.2` with better error handling to properly narrow to exact file that throws an error

**Comment by KajSzy** [comment]
Released new version with fix, now instead of throwing an error, every issue is logged into console (next to server)
Please provide example of thrown error in console
